apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: automation-runner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: automation
roleRef:
  kind: ClusterRole
  name: automation-clusterrole
  apiGroup: rbac.authorization.k8s.io